config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only:[:create,:new,:destroy]  #single resource because not in table
  resources :users
  resources :bands
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
    validates :email, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :session_token, presence: true
    validates :password,length: {minimum: 6, allow_nil: true}


    after_initialize :ensure_session_token

    def self.generate_sesssion_token
        self.session_token = SecureRandom.urlsafe_base64
    end

    def reset_session_token!
        self.session_token = SecureRandom.urlsafe_base64
        self.save
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64
    end

    def password
        @password
    end
    
    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end   

    def self.find_by_credentials(email,password)
        user = User.find_by(email: email)
        if user.nil? 
            return nil
        end

        user.is_password?(password) ? user:nil
    end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def login(user)
        @current_user = user
        session[:session_token] = user.reset_session_token!
    end

    def logout
        current_user.reset_session_token!
        session[:session_token] = nil
    end

    def current_user
        return nil unless session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index
        @bands = Band.all
        render :index
    end

    def new

    end

    def edit

    end

    def show
        @band = Band.find_by(id: params[:id])
        render :show
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:email],params[:user][:password])
        
        if @user
            login(@user)
            redirect_to user_url(@user)
        else
            @user = User.new(params[:user][:email],params[:user][:password])
            flash.now[:errors] = ["Invalid username or password combination"] #flash.now for render and redirect for other
            render :new
        end
    end

    def destroy
        logout
        render :new
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new
    end

    def index
        @users = User.all
        render :index
    end

    def show
        @user = User.find_by(id: params[:id])
        render :show
    end

    def create
        @user = User.new(user_params)
        # debugger
        if @user.save
            login(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages #flash.now for render and redirect for other
            render :new
        end
    end

    def destroy
        logout
        @user = User.new
        render :new
    end


    private
        #future use
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bands/index.html.erb
<div class="header">
<h1> List of our bands </h1>
    <ul>
        <%@bands.each do |band|%>
            <li><%=band.name%></li>
        <%end%>
    </ul>
</div>

app/views/bands/show.html.erb
<div class="header">
<h1> Band </h1>
    <ul>
       
            <li><%=band.name%></li>
   
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>

<div class="header">
  <h1>NotSpotify</h1>
  <p>Its a shitty spotify</p>
</div>

    <title>NotSpotify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
   <% if logged_in? %>
        <p>Welcome <%=@user.email%></p>
    <% else %>
        <a href="<%=new_session_url%>">Sign In!</a>  
        <a href="<%=new_user_url%>">Sign Up!</a>  
    <% end %>
     <%= yield %>
     <% if logged_in? %>
    <form action="<%=session_url%>" method="POST">

        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Log Out!">
    </form>
    
     <% end %>
    
  </body>
</html>

app/views/users/new.html.erb
<h1>Join our family!</h1>

<% if flash[:errors] %>
    <ul>
    <%flash[:errors].each do |err|%>
        <li><%=err%></li>
    <%end%>
    </ul>
<% end %>

<form action="<%=users_url%>"method="POST">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
<label>
    Enter your email(this will be your username):
    <input type="text" name="user[email]" value="<%@user.email%>">
</label>
<br><br>
<label>
    Enter your password(minimum 6 characters):
    <input type="text" name="user[password]" value="<%@user.password%>">
</label>
<br><br>
    <input type="submit" value="Join!">
</form>

app/views/users/show.html.erb
<h1>User Profile Page</h1>

<h2><%=@user.email%></h2>